### ISSUE TITLE
Transform all after FIRST

### ISSUE THREAD

**Issue by stuartrexking** [redplanetlabs/specter#288]
I'm working with a CSV file and I want to transform values and ignore the header.

I can use `(let [header & rows] csv)` but I'd like to be able to do this using specter without splitting out the headers separately.

Is there an idiomatic way of doing this?

**Comment by nathanmarz** [comment]
You can do something like this:

```clj
(def REST (srange-dynamic (fn [_] 1) count))
(transform [REST ALL] inc [1 2 3 4 5])
;; => [1 3 4 5 6]
```
