### ISSUE TITLE
Rename ALL to EACH

### ISSUE THREAD

**Issue by mbertheau** [redplanetlabs/specter#289]
I recently finally understood the approach of specter, after having first heard of it a few years ago. It's actually quite simple, once you're over the first bump.

One part that tripped me up in the beginning was ALL. I understand it now, but before I did, the name ALL didn't help me. specter always looks at all elements of a sequence, why do I need to specify that?

Now it is clear that ALL is way of saying "go one level deeper into the structure (without any further filtering or anything)", or "the structure is good up to here, now look at each of its elements".

I believe, EACH instead of ALL is more intuitive to read.

So I'm proposing to add EACH as an alias for ALL and use EACH instead of ALL in all the documentation.

**Comment by nathanmarz** [comment]
I think this is up for debate, but with the main goal of the project now being stability a rename/alias  is pretty much out of the question.
