### ISSUE TITLE
How to insert map at the end of a vector?

### ISSUE THREAD

**Issue by hermann-p** [redplanetlabs/specter#304]
I am trying

    (setval [:items END] {:foo "bar} {:items []}
    ;; {:items [[:foo "bar]]

But I would like (and expect) the result to be

    ;; {:items [{:foo "bar}]

What am I doing/understanding wrong?

**Comment by nathanmarz** [comment]
You're looking for `AFTER-ELEM`. `END` navigates to the empty subsequence.
