### ISSUE TITLE
Calling `first` on ALL MAP-VALS

### ISSUE THREAD

**Issue by WhittlesJr** [redplanetlabs/specter#305]
I wanted to transform this:
```
{:A {:a 1 :b 2} :B {:c 3 :d 4}}
```
Into this:
```
{:A [:a :b] :B [:c :d}
```
So I wrote this:
```
(transform [MAP-VALS ALL] first {:A {:a 1 :b 2} :B {:c 3 :d 4}})
```

But it threw this: 

```
Execution error (UnsupportedOperationException) at com.rpl.specter.navs/void-transformed-kv-pair? (navs.cljc:43).
count not supported on this type: Keyword
```

What did I do wrong? For now, I can just use this:

```
(encore/map-vals #(->> % (keys) (into [])))
```

But I'd like to know what's going on with Specter.

**Comment by WhittlesJr** [comment]
I realize I could also have just written 

```
(sp/transform [sp/MAP-VALS] #(->> % keys (into [])) {:opt {:a 1 :b 2} :opt-un {:c 3 :d 4}})
```

Which is pretty much the same thing as the encore version. But still, I'd like to know what's up with this error.

**Comment by nathanmarz** [comment]
When you do `ALL` on a map, it navigates you to the individual key/value pairs. As such, the outer structure remains a map and `ALL` is expecting the transforms of the key/value pairs to be either key/value pairs or `NONE`.
