### ISSUE TITLE
Remove all leaves that don't match a predicate

### ISSUE THREAD

**Issue by WhittlesJr** [redplanetlabs/specter#314]
I'm trying to remove leaves of a structure that don't match a predicate. I seemingly can't just `setval` to `NONE` with a  `walker` matching on  `(not (pred x))`, because that also selects branches that don't match the predicate, and leaves me with an empty collection. 

It would be ideal if I could somehow get the complement of a selection. Then I could use a `walker` on the `pred`, select everything not matched, and `setval` that stuff to `NONE`.

**Comment by WhittlesJr** [comment]
I would think that `(not (pred x))` should work, because it's depth-first... but the result is  that the whole collection is transformed into `sp/NONE` . 

If I just do `(setval (walker #(pred %) NONE m)`, it does remove the things that positively match. But I can't reverse that to _keep_ the things that match.

**Comment by WhittlesJr** [comment]
Oh, I understand why it fails with `not`, despite being depth-first. It navigates past the value to its parent key, and sets that to NONE.

**Comment by nathanmarz** [comment]
That's correct. I suggest making a custom `recursive-path` to have exact control.
