### ISSUE TITLE
are there plans to open source the maintained fork of specter?

### ISSUE THREAD

**Issue by xificurC** [redplanetlabs/specter#327]
As per [your blog post](https://tech.redplanetlabs.com/2021/06/03/tour-of-our-250k-line-clojure-codebase/) you have

> "rpl-specter", an internal fork of [Specter](https://github.com/redplanetlabs/specter) which adds a ton of functionality

Also curious what that _ton_ is

**Comment by nathanmarz** [comment]
We're not going to be open-sourcing our internal fork. The additional functionality is related to reactive select/transform operations we've implemented.

**Comment by xificurC** [comment]
Thanks for the quick response
