### ISSUE TITLE
Is there a way to collect a value and use it as part of the path?

### ISSUE THREAD

**Issue by WhittlesJr** [redplanetlabs/specter#331]
In this structure:
```clojure
{:config {:thing-order [:A :B :C]}
 :things {:A {:a "a"}
          :B {:b "b"}
          :C {:c "c"}}}
```

I want to make a path to "first thing." I want to go into `[:config :thing-order sp/FIRST` and grab that value to navigate to `[:things <my-key-here>]`. The result I want from my select is `{:a "a"}` These keys are not predictable so I can't use a cond-path. 

What options do I have? I can't find a way to do this by reading the wiki.

**Comment by nathanmarz** [comment]
There's no way to do that with built-in navigators, but this is possible by defining your own navigator with `defrichnav`. A "rich" navigator has access to all the collected values so far during navigation. Here's an example of using `defrichnav` from Specter's source: https://github.com/redplanetlabs/specter/blob/master/src/clj/com/rpl/specter.cljc#L945

That said, I would just do this with two select calls.

**Comment by WhittlesJr** [comment]
@nathanmarz , perfect, thank you! I'll report back here with the solution for posterity.

**Comment by WhittlesJr** [comment]
Here's the solution I'm going with:

```clojure
(sp/defrichnav collected-key []
  (select*    [this vals structure next-fn]
              (let [collected-key (first vals)]
                (if (contains? structure collected-key)
                  (next-fn vals (get structure collected-key))
                  sp/NONE)))
  (transform* [this vals structure next-fn]
              (let [collected-key (first vals)]
                (if (contains? structure collected-key)
                  (let [newkey   (get structure collected-key)
                        newval   (next-fn vals newkey)
                        dissoced (dissoc structure collected-key)]
                    (if (identical? sp/NONE newval)
                      dissoced
                      (assoc dissoced collected-key newval)))
                  structure))))

(def data
  {:config {:thing-order [:A :B :C]}
   :things {:A {:a "a"}
            :B {:b "b"}
            :C {:c "c"}}})

(def path
  [(sp/collect-one :config :thing-order sp/FIRST )
   :things
   collected-key
   sp/DISPENSE
   :a])

(sp/select-one path data)
;; => "a"

(sp/transform path (fn [s] (str s "-modded")) data)
;; => {:config {:thing-order [:A :B :C]},
;;     :things {:B {:b "b"}, :C {:c "c"}, :A {:a "a-modded"}}}


```
